"""Dump generated SQL vs gold for a few specific failing questions to diagnose
whether failures are real model errors or strict-comparison artifacts."""
import asyncio
from app.core.database import AsyncSessionLocal
from app.application.services.analyst_service import AnalystService

TARGETS = [
    "List all Gold tier customers.",
    "List all products in the Electronics category.",
    "Who is our single top customer by total order value?",
    "What are the top 3 best selling products by quantity sold?",
    "What is the total revenue generated by each customer from successful payments?",
    "What is the markup (price minus cost) for each product?",
]

async def main():
    async with AsyncSessionLocal() as db:
        svc = AnalystService(db)
        for nl in TARGETS:
            amb, clar, sql, _, _ = await svc.generate_sql(nl)
            print("\nQ:", nl)
            if amb or not sql:
                print("  -> CLARIFY:", clar)
                continue
            print("  GEN:", " ".join(sql.split()))
            try:
                _, rows, _ = await svc.execute_sql(sql)
                print(f"  ROWS({len(rows)}):", rows[:3])
            except Exception as e:
                await db.rollback()
                print("  EXEC ERR:", str(e)[:120])

asyncio.run(main())
